name:                hl7-parser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tmbull/hl7-parser#readme
license:             BSD3
author:              Tristan Bull
maintainer:          tristan.bull@goilluminate.com
copyright:           2017 Softek Illuminate Inc.
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

library:
  source-dirs: lib
  exposed-modules:
  - Lib
  dependencies:
  - text

executables:
  hl7-parser:
    source-dirs:      app
    main:             Main.hs

tests:
  parse-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hl7-parser
    - hspec
